services:
  e-esj-accueil-service:
    build: .
    container_name: e-esj-accueil-service
    ports:
      - '8080:8080'
    expose:
      - '8080'
  postgres-service:
    image: postgres:latest
    container_name: postgres_container-service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


